//
// Created by Ray on 2020/4/7.
//

#ifndef SQUIRLSIM_CONFIG_H
#define SQUIRLSIM_CONFIG_H

/** Controller parameters **/
#define CONTROLLER_NUMBER 1

/** Land parameters **/
#define LENGTH_OF_LAND 16
#define MONTH_LIMIT 24
#define LAND_RENEW_RATE 0.000002
#define LAST_POPULATION_MONTHS 3
#define LAST_INFECTION_MONTHS 2

/** Squirrel parameters **/
#define MAX_SQUIRREL_NUMBER 200
#define INITIAL_NUMBER_OF_SQUIRRELS 34
#define INITIAL_INFECTION_LEVEL 4
#define GIVE_BIRTH_STEPS 50
#define CATCH_DISEASE_STEPS 50
#define LAST_POPULATION_STEPS 50
#define LAST_INFECTION_STEPS 50

#endif //SQUIRLSIM_CONFIG_H
